version: 2

sources:
  - name: account_statements
    tables:
      - name: exports       
        external:
          location: "gs://bank-exports-prod/*.tsv"
          options:
            format: "CSV"
            skip_leading_rows: 1
            field_delimiter: "\t"
        columns:
          - name: data_contabile
            data_type: string
          - name: data_valuta
            data_type: string
          - name: importo
            data_type: string
          - name: descrizione
            data_type: string